### ISSUE TITLE
Error: Implement react-handsontable on mern.io stack

### ISSUE THREAD

**Issue by nvqchau** [handsontable/react-handsontable#41]
I add react-handsontable to mern.io stack but there is an error

> ReferenceError: document is not defined
    at Object.<anonymous> (/Users/chaunguyen/Projects/valuation.co/node_modules/react-handsontable/node_modules/handsontable/commonjs/helpers/browser.js:10:14)
    at Module._compile (module.js:635:30)
    at Module._extensions..js (module.js:646:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/chaunguyen/Projects/valuation.co/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/chaunguyen/Projects/valuation.co/node_modules/react-handsontable/node_modules/handsontable/commonjs/helpers/dom/element.js:50:16)
    at Module._compile (module.js:635:30)
    at Module._extensions..js (module.js:646:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/chaunguyen/Projects/valuation.co/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

Could anybody help me on this issue?

**Comment by jehunter5811** [comment]
Hey @nvqchau I'm not using express, but I am running this on Node in React. It's working for me, so I'm wondering if you could share your component code rather than just the error?

**Comment by AMBudnik** [comment]
I think that we can close the issue as there is no response from the author for more than 2 weeks

**Comment by nvqchau** [comment]
Hi,

Actually, I am working on NextJS and I think the issue is: Server Side Rendering because it works well on Client Side Rendering.

Cheers,

On Jan 13, 2018, at 11:32 AM, jehunter5811 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @nvqchau<https://github.com/nvqchau> I'm not using express, but I am running this on Node in React. It's working for me, so I'm wondering if you could share your component code rather than just the error?
